language:
- python
os:
- linux
dist:
- xenial
cache:
- pip
- bundler
- directories: "/home/travis/.rvm/"
before_install:
# - rvm install 3.1.0
- rvm install 3.0.0
install:
- pip install pandas
before_script:
- bundle install --retry 3
- chmod +x ./script/cibuild
script:
- "./script/cibuild"
after_success:
- bundle exec travis-custom-deploy sftp _site/idlab/
env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
  # travis encrypt DEPLOY_HOST="cmci.colorado.edu" --add
  # travis encrypt DEPLOY_USERNAME="jebr8899" --add
  # travis encrypt DEPLOY_PASSWORD="XXXXXX" --add
  # travis encrypt DEPLOY_REMOTEDIR="/data/web/htdocs/idlab/" --add
  - secure: wAiaR07+0CVnFDuiR79c7iCfDcDJjmZYSiC/OUB3Q3OVU/LUmx400wltkPLrDKoz4r3+zjSMIThiw2vuk7xfDqVTm6cU9hFXX17lpl92srfMmljzzBsA+9qFICrrGju3kkhWJzlbTXGNnstkELg3DJIbyqMc/rHrXiUVpTCVxn2hPUGecyQoWvj3bjZmtAqgaSdGhDnO31q+vRbZ1osSj7iY6Cgwphl04XNSrnULlye7gwGVbRUX6v8bjOnEVj/ex500wxU+4MPXJKO2y0BaEC6L2weY5rVcZZnIo45ZDqMlyoqdS02drxEfoAp37r7LRnUxio++pCWdTviG1P3iRtpgX6E/3qQDxDsnw+IEE/EIl6kWFHFSmmXk8W+UnkwhQsaaBY8ue7GMq3HNvuZ6FJbqwqcTuLr3iH/FgJGNnxVTsGD91Tqzql2Ke5G0/xySq5lJgD8GEozJa/oiOwv5+nWcEcFTIB0tmMXaq6t6fbVGb1+fhUUjUrLLr0qkejdbPkidfK3w+r3hmCzLgrD+dBHQmk4msgwA+Vrfyt6byMHqLS5pgtjJUsY8uUQEYTu/9iVc5aanmvA0+HzXY4fk+CHqPM5gRcmQaWoW5EvHLyyBA1pAFCP8Q1gdGaiYZJJ4HHBKJmKt/Oilyw2U4kJyIeiKrME1WIyf2cAhmbgF6VY=
  - secure: r7su4Ft6EfyRCZJE1wqjAFOv/oivoKD8ghHt2GK1OJGbmKBX0oSzHlbFdSvYINqQeoJHNodcFHe5UzoUshtvZNI+ZyX3YO7xPilIsibvRXLhYD6y4NzctOBF0ohWDvpXIIdxj6n3NcynhueH8py472nPgNs4QBZEQRMSewyWRfOvkQrkmnZf8hcLkHG3j0R69XpFb1wTlKL78BS3/YkMV28Ac9DFoU05mX4DG3GiE9AxPeUd6HJzZXTldcEGLThOMDPB+x60gpYjUR1D5RnfG9NuzO41WVd0OtNhNFTW8SqfQumEOoMf0TywxZUZmmsab1eWDZpf+8tjUDzRrcM+MpVxPX5WQxriboEbWcYZgFqARk57ApfuUcj34HW9tIsW0cl1aZQUwpYBjvL31VL8iZh+so4JQ4u/o2dCc5l1m2w43XTaxCczo0OQ3hfBYsHsKrQjPEDoNQ7ZSU0miIoeMLhqfHBN9gND58oEqEDL3aU8ayFopPlE0bihgU1ecwlfwtcuVV4mEufmacjJAmyg+ny9Er6iCBEj9nNcESBFaR1jgA6zUGwNOC3+zysl0qLYOScPhix3EIcCZEpYNjm7AdttAkCFEklq7dzwbcBM7TmIsIBjKgWT0B3x53urnIpNGnzxMBJkMt2k4+BwNYkUR6MTDZDMomV+kkJZ0N1AXys=
  - secure: sgnRGQDMQzSI985Ph1E+PFs1FbABvZz6HMQYP67ypLMZkW5KwylyS4sRXF5vahIRtnwNIF1SlLBp4jiErWPQueHDXtCh+9fxyBZ3BEE8jh6AuyHBvGeUJGuu3uuorwjK+uwlcgq9bapsB/C/IZR81C6GTug95sTh/6HjREDSJeyCB3ta9gYTW/yvGi0VCA0mqf8G1TLneczEnIxysAZwa5oQXj7B2MsSVYOi+t4gevlIXETJ8CTrvnOkkCLZqdGh1DMzJX6DJeWfhPkDI3bTv37qVYIHMjVj/jLaYeBXfb6onaS+qN8yCEZRKPiYdUaVDeP9gxd03ntfIDs6XA+hWocNMQcjF16+96x2LH0Byr6FVJAJrcbiW8OWRmMonXKW+vJM4rJ8DPpgdgyKE2JHqQ4Zs5mei0A+a4vWKhDcggVsscxvWaQ4QQgwz+zBHzkKmwx+/s9NDkNg8BmGm9aGpw2EvHPsfo0O05Xrc8BMBU3GG1dHdWiKThtR1Mt0IAjER3UlaHGaq3Lfe/FAO/faPgnf5fWylSvjrL+/EuwUtFvnMl2n1di+QXgzlny98XBVm7wap1HE/+xDIcUagVNlVCVuqDaKriHDoq8TeXsh33B1velrG6g6OPbMb5GMm5+olPwzbK4MT72Qaq1lqfT1L40o9AfpcHyFl4krtRxAOL4=
  - secure: QoTkuED575IcHCXBlNG/PqIrZJVmSzrPey+jSpARZ+aWflbYKhq1S0MNqax9qOXM9dJj1dEO1vAhXzXerWrU/j4uH9te6miSMw9Rd9lQZcZCW3bMxLTp8M6CbLEn8+b9UsYvBu82acZiJMJ2PzfRvdffWVJAKOVGF0eu50s+fEYEtfj2SsvrxFJSKLzbved3YrEGUUMczHrNHC7d7vZ+fP+i+aDPKcZ6a/+Tsym8K/lXsV/WH1pJ2bBG5gVVh9fuRT7Lwp9DN1yrq07lnC3MMtHo5Umv8NJUcJtx5c5khgt2iThBKw+O7oj7EvV4GmDVdWaQ+h0AHXZa+bPf/EayF4fj8/FkgZUDOdzZP7Xac8c50P9LhAfHHjgYrChbINmX52XV5LGdLV0vOV7oa641iDvgOO15Dn1zzHOhSfqE5v1A5As05cZhDS3Mw5wndZBXyQXLqBuwx4mzn6XA6HNoJVR2iZRZLZkOkxGFisIkAWApEJVHkaO089oHawWsflv2SUSxw4hVvn5I59hGBMcgkzd5VeJeCrW70NuYUiRlYJtfHzB8NYpaotb2HpbBgXyzomKziezyd61Acc7W1erOB++NWCMRMCvmZXx8Vyv2ieLKF+CHDB9KFew8oUz15Mlq2WN7GkVB/4HLiu5UqR3ejS0E6NwJr0I0MzVR34ZIu1c=
# notifications:
#   slack: cu-infosci-labs:rss7NJ96a0HtVXCYbZxrLJcy
