# Site settings
title: Identity Lab @ CU Boulder
email: jed.brubaker@colorado.edu
description: > # this means to ignore newlines until "baseurl:"
  We study how identity is designed, represented, and experienced through technology.
  The Identity Lab is led by Jed Brubaker, Associate Professor of Information Science in CU Boulder's college of Media, Communication, and Information.
baseurl: "" # Remove subpath for GitHub Pages
url: "https://www.cuidentitylab.com" # Your custom domain
# twitter_username: jekyllrb
github_username:  cu-idlab

# Site sections
include: ["_pages", "_projects"]
permalink: /:title/

# Build settings
markdown: kramdown

paginate: 4
paginate_path: "blog/page:num"

# Defaults
defaults:
  -
    scope:
      type: "pages"
    values:
      category: "page"

# Plugins
plugins: [jekyll-paginate, jekyll-seo-tag, jekyll-sass-converter]

# Scholar
scholar:
  style: assets/bibliography/sigchi.csl
  locale: en

  sort_by: year, author
  order: descending

  source: assets/bibliography
  repository: assets/bibliography/pdf
  bibliography: lab
  bibliography_template: reference

  replace_strings: true

  # details_dir:    publications
  # details_layout: publication.html
  # details_link:   Details

  query: "@*"
