#!/usr/bin/env bash
set -x # Show the output of the following commands (useful for debugging)
set -e # halt script on error
bundle exec jekyll build -d _site/idlab
# bundle exec htmlproofer ./_site
# bundle exec htmlproofer ./_site --only-4xx --check-favicon --check-html --allow-hash-href
# scp -r ./_site/idlab/* jebr8899@cmciweb.colorado.edu:/data/web/htdocs/idlab/
