name: Jekyll Build and Release

on:
  push:
    branches:
      - prod

jobs:
  build_and_release:
    runs-on: ubuntu-latest
    env:
      JEKYLL_ENV: production

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '2.7'

    - name: Install Jekyll and dependencies
      run: |
        gem install bundler
        bundle install

    - name: Build Jekyll site
      run: bundle exec jekyll build

    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: jekyll-site
        path: ./_site

    - name: Create release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: v${{ github.run_number }}
        release_name: Release v${{ github.run_number }}
        body: |
          Release for commit ${{ github.sha }}.
        draft: false
        prerelease: false

    - name: Upload artifact to release
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./_site
        asset_name: jekyll-site.zip
        asset_content_type: application/zip
